### ISSUE TITLE
图形上能响应点击事件么

### ISSUE THREAD

**Issue by wweyl** [guyoung/streakjs-weapp#1]

**Comment by qinshou** [comment]
ZRender有这个[API](https://ecomfe.github.io/zrender-doc/public/api.html#oneventname-eventhandler-context)，但是实际在小程序测试没有效果

**Comment by tianzhipeng-git** [comment]
小程序没有浏览器那种事件了, 必须用小程序那种方式绑定吧.
我看到zrender-helper.js里面_initEvent方法做了处理, 但是不知道怎么起作用, 这个可能要作者解释一下了.

我模仿着这样写的, it works:

首先在wxml里 bindtouchstart="ctap"

然后js在ctap函数: 
```
function (e) {
          let touch = e.touches[0];
          zr.handler.dispatch('mousedown', {
            zrX: touch.x,
            zrY: touch.y
          });
}
```

然后在zr对应图形或整个示例上on 'mousedown' 这个事件.

**Comment by spiritzx** [comment]
clientX

> 小程序没有浏览器那种事件了, 必须用小程序那种方式绑定吧.
> 我看到zrender-helper.js里面_initEvent方法做了处理, 但是不知道怎么起作用, 这个可能要作者解释一下了.
> 
> 我模仿着这样写的, it works:
> 
> 首先在wxml里 bindtouchstart="ctap"
> 
> 然后js在ctap函数:
> 
> ```
> function (e) {
>           let touch = e.touches[0];
>           zr.handler.dispatch('mousedown', {
>             zrX: touch.x,
>             zrY: touch.y
>           });
> }
> ```
> 然后在zr对应图形或整个示例上on 'mousedown' 这个事件.

代码应该是这样的才有作用
function (e) {
>           let touch = e.touches[0];
>           zr.handler.dispatch('mousedown', {
>             zrX: touch.clientX,
>             zrY: touch.clientY
>           });
> }
