### ISSUE TITLE
是否可以用另一种思路来使用这个扩展或者实现另一种扩展？

### ISSUE THREAD

**Issue by jane00** [guyoung/streakjs-weapp#2]
具体是指的把现在的WX的canvas扩展为与HTML5原生canvas一样的接口和特性。这样原来的基于html5的canvas的库都可以直接port了。

**Comment by jane00** [comment]
其实我的目的是问这个库是否可以结合createJS一起使用？感谢。

**Comment by jane00** [comment]
还是本来就可以？跟这个扩展没关系？

**Comment by wafj999** [comment]
我也想知道 我之前是用createjs在flash里面弄得动画 想导入到微信小程序里面可惜不知道怎么弄
